version: '3.4'

services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=ex_mon_api_dev
    volumes:
      - database-data:/var/lib/postgresql/data/ 
    ports:
      - "5432:5432"

volumes:
  database-data: 
